# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.define "web" do |web|
  web.vm.hostname = "web"
  end

  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
    db.vm.hostname = "db"
  end

  config.vm.define "cache" do |cache|
    cache.vm.box = "hashicorp/precise64"
    cache.vm.hostname = "cache"
  end

  (1..4).each do |index|
    config.vm.define "server#{index}" do |server|
      server.vm.hostname = "server#{index}"

      server.vm.provider "vmware-desktop" do |vmw|
        vmw.name = "svr#{index}"
      end

      server.vm.network "private_network", ip: "192.168.33.#{index}"

    end
  end

end
