- hosts: all
  tasks:
    - ansible.builtin.debug:
        msg: "Installing the most package for manual pager and setting it as default PAGER"
    - name: "use most as default PAGER"
      ansible.builtin.lineinfile:
        path: "/home/vagrant/.bashrc"
        line: "export PAGER=most"

- name: "package installs"
  hosts: all
  become: true
  tasks:
    - ansible.builtin.apt:
        update_cache: true
        name: most
